name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build binary
      run: |
        GOARCH=arm64 go build -o nannyapi ./cmd/main.go

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: nannyapi
        path: nannyapi
  
  deploy:
    runs-on: [self-hosted, linux, ARM64]
    needs: build

    steps:
    - name: Download binary
      uses: actions/download-artifact@v2
      with:
        name: nannyapi
        path: /home/ubuntu/actions-runner/_work/nannyapi

    #- name: Deploy binary
    #  run: |
    #    sudo systemctl restart nannyapi.service